### ISSUE TITLE
"ecsFormat is not a function" when using elastic-apm-node

### ISSUE THREAD

**Issue by Lalaluka** [elastic/ecs-logging-nodejs#79]
Hi 👋

While adding elastic logging to a Node.js Application I encountered an Error using it together with ecs-pino-nodejs.

Error stack: 
```
TypeError: ecsFormat is not a function
    at Object.createLogger (/Users/****/devPers/git/elk-pino-bug/node_modules/elastic-apm-node/lib/logging.js:142:8)
    at new Config (/Users/****/devPers/git/elk-pino-bug/node_modules/elastic-apm-node/lib/config.js:260:27)
    at config (/Users/****/devPers/git/elk-pino-bug/node_modules/elastic-apm-node/lib/config.js:222:10)
    at Agent._config (/Users/****/devPers/git/elk-pino-bug/node_modules/elastic-apm-node/lib/agent.js:145:16)
    at new Agent (/Users/****/devPers/git/elk-pino-bug/node_modules/elastic-apm-node/lib/agent.js:38:8)
    at Object.<anonymous> (/Users/****/devPers/git/elk-pino-bug/node_modules/elastic-apm-node/index.js:5:18)
```
How to Reproduce:
index.js:
```
const ecsFormat = require('@elastic/ecs-pino-format')
const pino = require('pino')
const ElasticAPM = require('elastic-apm-node')

const apm = ElasticAPM.start({
	serviceName: 'serviceName',
})

const logger = pino({ ...ecsFormat({ convertReqRes: true, convertErr: true, apmIntegration: true }) })

logger.info("Test")
```
Run with `node index.js`
Installed Packages:

- @elastic/ecs-pino-format v.1.1.1
- elastic-apm-node v3.14.0
- pino v6.11.3
Running Node 14.15.5

Interestingly enough I can work around that issue using an Alias dependency. If I install ecs-pino-format like this: 
`npm i ecs-pino-format@npm:@elastic/ecs-pino-format`

And change line 1 to 
`const ecsFormat = require('ecs-pino-format')`

It runs perfectly. 

I'm not sure if it's an issue with elastic-apm-node, the pino-logger itself, or I configured something wrong.
Could someone assist me with this issue?

**Comment by trentm** [comment]
@Lalaluka Thanks! Yes, I'm able to reproduce. This is a circular-require bug:
- this package optionally imports 'elastic-apm-node' to use it to enrich log records; and
- 'elastic-apm-node' (since v3.13.0) uses this package for its logging

If you end up with a `node_modules/...` that results in both one's application code and 'elastic-apm-node' sharing the same `@elastic/ecs-pino-format`, then this happens.

I've chosen to fix this by having the `require('elastic-apm-node')` be lazily done here, which I hope is reasonable. An alternative would be to have the 'elastic-apm-node' package vendor its own namespaced version of this logging package, which would be more maintenance work.

**Comment by trentm** [comment]
Once CI passes I'll try to get a new release out soon.

**Comment by trentm** [comment]
`@elastic/ecs-pino-format@1.1.2` published with a fix for this. @Lalaluka I'd love to know if this fixes the issue for you (it should, but confirmation is nice. :)

**Comment by Lalaluka** [comment]
Hey, 
first: thanks for the super-fast fix :D

I tested in plain javascript and as well in Typescript (where the issue first occurred with @types/pino).
And it works like a charm 💎
Thanks again
